name: Submit Weekly
on: [workflow_dispatch]
jobs:
  submit_weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip wget
      - name: Install the pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb
          sudo dpkg -i pandoc-2.17.1.1-1-amd64.deb
      - name: Run submit weekly script
        run: ./.github/scripts/submit_weekly.sh
        shell: bash
      - name: Submit the email to big boss and little boss
        # see https://github.com/dawidd6/action-send-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yandex.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "${{env.WEEKLY_NAME}}"
          to: ${{secrets.BIG_BOSS_EMAIL_ADDRESS}}
          from: ${{secrets.MAIL_USERNAME}}
          secure: true
          html_body: file://./Template/email.md
          cc: ${{secrets.LITTLE_BOSS_EMAIL_ADDRESS}}, ${{secrets.SELF_MAIL_ADDRESS}}
          ignore_cert: true
          convert_markdown: true
          attachments: ./${{env.WEEKLY_PATH}}/${{env.WEEKLY_NAME}}
          priority: normal
